language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - cd tests
  - mysql -u root -e 'CREATE SCHEMA `yii`; GRANT ALL ON `yii`.* TO test@localhost IDENTIFIED BY "test"; FLUSH PRIVILEGES;'
  - mysql -u root -D yii < framework/db/data/mysql.sql
  - pgsql -c 'CREATE ROLE test WITH PASSWORD 'test' LOGIN; CREATE DATABASE yii WITH OWNER = test; GRANT ALL PRIVILEGES ON DATABASE yii TO test;' -U postgres
  - pgsql -d yii -f framework/db/data/postgres.sql -U test
  - pgsql -d yii -f framework/web/auth/schema.sql -U test
  - pecl install memcache
  - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s/.*:\s*//"`

script: phpunit --verbose --coverage-html reports framework
